define THLD_MOD_NAME = "thld"
define THLD_PREFIX = THLD_MOD_NAME + "_"

define THLD_TIMEOFDAY_DAY = "day"
define THLD_TIMEOFDAY_NIGHT = "night"
define THLD_TIMEOFDAY_SUNSET = "sunset"
define THLD_TIMEOFDAY_PROLOGUE = "prologue"

define THLD_PACIFIST_NAME_COLOR = "#088010"
define THLD_PI_ARENA_NAME_COLOR = "#4b0287"
define THLD_TEAPOT_NAME_COLOR = "#551313"
define THLD_PI_RAILWAY_NAME_COLOR = "#e09590"
define THLD_PREACHER_NAME_COLOR = "#f7eded"
define THLD_THIRD_NAME_COLOR = "#004979"
define THLD_PI_ANNOUNCER_NAME_COLOR = "#af9151"
define THLD_BUTCHER_NAME_COLOR = "#9a3e3e"
define THLD_PI_PHAROS_NAME_COLOR = "#2ad2db"
define THLD_ENGI_NAME_COLOR = "#ba753f"
define THLD_GENSEK_NAME_COLOR = "#d1d141"
define THLD_CROWD_NAME_COLOR = "#66584d"
define THLD_PI_GUIDE_NAME_COLOR = "#377294"

define THLD_GUI_PATH = "thld/images/gui/"

define THLD_SAVE_LOAD_EMPTY_LABEL = " Пусто"
define THLD_SAVE_LOAD_FORMAT = " %d.%m.%y, %H:%M"

define THLD_SCREENS = [
    "main_menu",
    "quit",
    "say",
    "nvl",
    "game_menu_selector",
    "yesno_prompt",
    "choice",
    "help",
]

define THLD_CHOICE_COLORS = {
    THLD_TIMEOFDAY_DAY: "#466123",
    THLD_TIMEOFDAY_NIGHT: "#145644",
    THLD_TIMEOFDAY_PROLOGUE: "#496463",
    THLD_TIMEOFDAY_SUNSET: "#69652f",
}

define THLD_CHOICE_COLORS_HOVER = {
    THLD_TIMEOFDAY_DAY: "#9dcd55",
    THLD_TIMEOFDAY_NIGHT: "#3ccfa2",
    THLD_TIMEOFDAY_PROLOGUE: "#98d8da",
    THLD_TIMEOFDAY_SUNSET: "#dcd168",
}

define THLD_CHOICE_COLORS_SELECTED = {
    THLD_TIMEOFDAY_DAY: "#2a3b15",
    THLD_TIMEOFDAY_NIGHT: "#0b3027",
    THLD_TIMEOFDAY_PROLOGUE: "#2d3d3d",
    THLD_TIMEOFDAY_SUNSET: "#42401e",
}

define THLD_TEXT_HISTORY_WHAT_COLOR_HOVER = {
    THLD_TIMEOFDAY_DAY: "#40e138",
    THLD_TIMEOFDAY_NIGHT: "#008193",
    THLD_TIMEOFDAY_PROLOGUE: "#00c6ff",
    THLD_TIMEOFDAY_SUNSET: "#636840",
}

define THLD_YESNO_PROMPT_MESSAGE_COLOR = {
    THLD_TIMEOFDAY_DAY: "#64483c",
    THLD_TIMEOFDAY_NIGHT: "#161d3d",
    THLD_TIMEOFDAY_PROLOGUE: "#008193",
    THLD_TIMEOFDAY_SUNSET: "#5a3525",
}
